In [1]:
import random

In [44]:
a = random.random()
print(a) #This will print a random float number between 0 to 1

0.9976939089041842


Suppose we want random float value between a certain range

In [5]:
b = random.uniform(5,10)
print(b) 

6.463361311329648


Suppose we want random integer between a certain range

In [10]:
c = random.randint(5,10) #This may pick up 10 as output
print(c) 

6


suppose if we want to avoid the last index

In [9]:
c = random.randrange(5,10)
print(c) # This will never pick up 10 as output 

6


We can generate Normalized random value

In [18]:
d = random.normalvariate(0,1) # This will take a mean 0 and standard deviation of 1
print(d)

-1.034119557130582


In [19]:
import random

In [39]:
my_list = list('ABCDEFGH')
e = random.sample(my_list,3) #This will pick unique elements
print(e)

['E', 'F', 'B']


In [43]:
my_list = list('ABCDEFGH')
f = random.choices(my_list, k=3) #If a element can be picked multiple times
print(f)

['C', 'H', 'C']


In [46]:
my_list = list('ABCDEFGH')
random.shuffle(my_list) #This will shuffle the elements in our list
print(my_list)

['B', 'C', 'H', 'A', 'F', 'D', 'G', 'E']


In [49]:
random.seed(1)

print(random.random())
print(random.randint(1,10))


0.13436424411240122
2


In [51]:
random.seed(1)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2


In [52]:
random.seed(2)
print(random.random())
print(random.randint(1,10))

0.9560342718892494
1


In [53]:
random.seed(2)
print(random.random())
print(random.randint(1,10))

0.9560342718892494
1


They produce exact same output if the seed value is true. But due to security purposes they are not good to use

In [54]:
import secrets

In [62]:
print(secrets.randbelow(10)) #10 is exclusive
print(secrets.randbits(4)) #1111 is most possible with 4 bites - range (0,15)
print(secrets.choice(my_list)) 


4
12
G


In [1]:
import numpy as np

In [2]:
print(np.random.rand(3))

[0.54163803 0.86128411 0.21200389]


In [3]:
print(np.random.rand(3,3))

[[0.98660884 0.71737591 0.54639474]
 [0.95427775 0.82878077 0.66931361]
 [0.30310228 0.38167953 0.07953885]]


In [9]:
print(np.random.randint(1,5,2))

[1 1]


In [7]:
print(np.random.randint(0,10,(2,2)))

[[9 7]
 [7 9]]


In [10]:
np.random.seed(1)

In [13]:
np.random.rand(1)

array([0.417022])

In [15]:
np.random.seed(1)
np.random.rand(1)

array([0.417022])

Python random function and Numpy random function will both use a different seed functions 